modelName = 'FlatStatus'
fields = [('_id', '_id', 'Int64'),
          ('account_key', 'accountKey', 'UserKey'),
          ('status_id', 'id', 'String'),
          ('created_at', 'createdAt', 'NSDate'),
          ('user_key', 'userKey', 'UserKey'),
          ('user_name', 'userName', 'String'),
          ('user_screen_name', 'userScreenName', 'String'),
          ('user_profile_image', 'userProfileImage', 'String'),
          ('text_plain', 'textPlain', 'String'),
          ('text_display', 'textDisplay', 'String'),
          ('is_gap', 'isGap', 'Bool'),
          ('metadata', 'metadata', 'Metadata'),
          
          ('quoted_status_id', 'quotedId', 'String'),
          ('quoted_user_key', 'quotedUserKey', 'UserKey'),
          ('quoted_user_name', 'quotedUserName', 'String'),
          ('quoted_user_screen_name', 'quotedUserScreenName', 'String'),
          ('quoted_user_profile_image', 'quotedUserProfileImage', 'String'),
          ('quoted_text_plain', 'quotedTextPlain', 'String'),
          ('quoted_text_display', 'quotedTextDisplay', 'String'),
          ('quoted_metadata', 'quotedMetadata', 'Metadata')]